### ISSUE TITLE
Possible to include folder names (if they have a date) as well?

### ISSUE THREAD

**Issue by StuffonGithub** [Serene-Arc/timestamp-converter#1]
Firstly, can I just say you are an extremely awesome human being for making this and taking the time to help a stranger out. 😊

I did a test run using the code you provided in the readme (thank you for that one as well by the way) and it worked flawlessly! Luckily though, the test folder I ran it on had a couple sub-folders (for the multiple images in a single post stuff I assume) where the folder names follow BDFR's naming scheme setup instead of the individual files inside it (which isn't a problem since I think the root folder naming is the most important one for sorting anyway).

Nevertheless, is there a way to make the script rename the sub-folders that have dates in their name as well? Not a big deal if it doesn't, just wanted to ask if possible to try and keep uniformity. 😅

Thanks again!

**Comment by Serene-Arc** [comment]
I update the README with a command that will rename folders. Note that if you do that, then you can't do the recursive bit because the program will crash since the files it knows about will have moved. Hopefully that isn't too much of a problem

**Comment by StuffonGithub** [comment]
Thanks! It's unfortunate that the folder has to be done individually but it's better than having to do it manually. I should be able to figure out a way to auto-create a .ps1 file for the command line needed for each folder.

Thank you so much for indulging me, @Serene-Arc! 🥰

**Comment by Serene-Arc** [comment]
@StuffonGithub no it has to be done one *containing* folder at a time, sorry. So if you have your downloads in a folder, and there are a thousand folders, each with a thousand files, you can do all the folders in the root folder in a single command, and then all the files with the `--recursive` option.

So it's more accurate to say that you can only rename one level in a filesystem if you include the folders. There are ways around that with programs like `find` on Linux that use a depth-first search system but I didn't implement that how I normally would since I knew you were on Windows. If `find` or an analog is available on Windows, then I can give you commands that would make this easier.

**Comment by StuffonGithub** [comment]
@Serene-Arc Yeah, it's no problem, you've done more for me already. 😊 Something like `find` would actually be nice but what I had in mind was basically just something that automatically gets the path of all folders in the root then have another script create .ps1 files changing the `DESTINATION` bit of the command. Then I'll just run the .ps1 scripts. Haha. It's a bit of a workaround but that was my though. Haven't gotten around to it anyway. 😁

**Comment by Serene-Arc** [comment]
@StuffonGithub If you'd like I can retool the algorithm to be depth first so it would solve this problem? It would be a pretty minimal change

**Comment by StuffonGithub** [comment]
@Serene-Arc It's quite alright. It's your tool so it's up to you. I just don't wanna come off as demanding features and cause extra work since you've been incredibly helpful to me. 😊 I should be able to make do with a workaround, haha.

**Comment by Serene-Arc** [comment]
Alright well if you have a workaround that works I'll leave it at this :)
